version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0

    working_directory: ~/workoutapp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: yarn run build

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
    # - deploy-job:
    #     requires:
    #         - build-job
    #     filters:
    #         branches:
    #         only: master
